### ISSUE TITLE
Can be used with itorch?

### ISSUE THREAD

**Issue by giahung24** [rotmanmi/word2vec.torch#3]
Hello,

I want to "play" around with itorch and your tools. But when i tried the first line of code to create the w2utils instance

> local w2vutils = require 'w2vutils'

the console gave me this error of "module not found". I was running itorch in the same directory of w2utils and bintot7.lua.

I am very new to lua and torch, can you give some clues about this?
Thanks in advance!

> ./w2vutils.lua:9: module 'bintot7.lua' not found:
>   no field package.preload['bintot7.lua']
>   no file '/home/jean/.luarocks/share/lua/5.1/bintot7/lua.lua'
>   no file '/home/jean/.luarocks/share/lua/5.1/bintot7/lua/init.lua'
>   no file '/home/jean/torch/install/share/lua/5.1/bintot7/lua.lua'
>   no file '/home/jean/torch/install/share/lua/5.1/bintot7/lua/init.lua'
>   no file './bintot7/lua.lua'
>   no file '/home/jean/torch/install/share/luajit-2.1.0-beta1/bintot7/lua.lua'
>   no file '/usr/local/share/lua/5.1/bintot7/lua.lua'
>   no file '/usr/local/share/lua/5.1/bintot7/lua/init.lua'
>   no file '/home/jean/torch/install/lib/bintot7/lua.so'
>   no file '/home/jean/.luarocks/lib/lua/5.1/bintot7/lua.so'
>   no file '/home/jean/torch/install/lib/lua/5.1/bintot7/lua.so'
>   no file './bintot7/lua.so'
>   no file '/usr/local/lib/lua/5.1/bintot7/lua.so'
>   no file '/usr/local/lib/lua/5.1/loadall.so'
>   no file '/home/jean/torch/install/lib/bintot7.so'
>   no file '/home/jean/.luarocks/lib/lua/5.1/bintot7.so'
>   no file '/home/jean/torch/install/lib/lua/5.1/bintot7.so'
>   no file './bintot7.so'
>   no file '/usr/local/lib/lua/5.1/bintot7.so'
>   no file '/usr/local/lib/lua/5.1/loadall.so'
> stack traceback:
>   [C]: in function 'require'
>   ./w2vutils.lua:9: in main chunk
>   [C]: in function 'require'
>   [string "w2vutils = require 'w2vutils'..."]:1: in main chunk
>   [C]: in function 'xpcall'
>   /home/jean/torch/install/share/lua/5.1/itorch/main.lua:179: in function </home/jean/torch/install/share/lua/5.1/itorch/main.lua:143>
>   /home/jean/torch/install/share/lua/5.1/lzmq/poller.lua:75: in function 'poll'
>   /home/jean/torch/install/share/lua/5.1/lzmq/impl/loop.lua:307: in function 'poll'
>   /home/jean/torch/install/share/lua/5.1/lzmq/impl/loop.lua:325: in function 'sleep_ex'
>   /home/jean/torch/install/share/lua/5.1/lzmq/impl/loop.lua:370: in function 'start'
>   /home/jean/torch/install/share/lua/5.1/itorch/main.lua:350: in main chunk
>   [C]: in function 'require'
>   (command line):1: in main chunk
>   [C]: at 0x00406670

**Comment by rotmanmi** [comment]
Hi giahung24,

Do you encounter the same problem when you run the the same command from the 'th' interpreter?

When I run the package from iTorch, it's working fine.

Thanks,

rotmanmi

**Comment by giahung24** [comment]
Hi,
I have abandoned after hours of testing so I don't remember much.
Apparently,  it worked well when i edit the source code of 'require' (maybe the problem of incompatible version..)
Thanks,
Jean
